### ISSUE TITLE
./configure missing

### ISSUE THREAD

**Issue by VSilantyev** [emcrisostomo/fsw#1]
The INSTALL file refers to ./configure script.
There is no such file.

How can I compile fsw on osx ?

**Comment by emcrisostomo** [comment]
Hi,

`configure` is a script automatically generated by the GNU Build System and this kind of files should  not generally be tracked by source control management systems (GitHub in this case).

If you grab the sources (as I think you're doing), you can bootstrap the GNU Build System using the `autogen.sh` script: `configure` will be generated alongside all the required files to build `fsw` on your platform.

However, this process requires the GNU Build System to be installed on your machine and is indicated only to developers who want to build the sources.

If you just want to build `fsw`, you should grab a release tarball (I just updated v. 1.2.0): release tarballs package the sources and all the things you need to build `fsw`.

To get a release tarball:
- Navigate to the repository of `fsw`
- Choose _Releases_ in the header above the source listing (_fsw v. 1.2.0_ should appear by default in this moment).
- Scroll down to the end of the release description and click the _fsw-1.2.0.tar.gz_ **green** button.

Let me know if you still have problems.

Cheers,
Enrico M. Crisostomo

**Comment by VSilantyev** [comment]
Thanks, it works

**Comment by emcrisostomo** [comment]
You are welcome.

Cheers,
Enrico M. Crisostomo
