### ISSUE TITLE
Support executing a command on changed event

### ISSUE THREAD

**Issue by remko** [emcrisostomo/fsw#11]
fswatch's documentation claims to be able to run a command when files change. Looking at the code, it doesn't seem like it does, but it would have been a useful feature anyway (maybe it used to support it). I want to trigger actions when files change.

**Comment by remko** [comment]
Found the other fswatch.

**Comment by emcrisostomo** [comment]
Hi @remko.

Yes, in fact `fsw` has merged with `fswatch`. By the way, neither is able to run a command: the first `fswatch` iterations had this feature but it was dropped. Now, `fswatch` prints change _events_ that you can use as triggers.

**Comment by remko** [comment]
Thanks @emcrisostomo. I worked it out from the example, it solved my problem.
